episodes/001/README.md
episodes/002/README.md
episodes/003/README.md
episodes/004/README.md
episodes/005/README.md

Porting first five episode from recollir/tgik-playlist

First five episodes

---

episodes/006/README.md
episodes/007/README.md
episodes/008/README.md
episodes/009/README.md
episodes/010/README.md

Porting episode 006-010 from recollir/tgik-playlist

Episode 006-010

---

episodes/011/README.md
episodes/012/README.md
episodes/013/README.md
episodes/014/README.md
episodes/015/README.md

Porting episode 011-015 from recollir/tgik-playlist

Episode 011-015

---

episodes/016/README.md
episodes/017/README.md
episodes/018/README.md
episodes/019/README.md
episodes/020/README.md

Porting episode 016-020 from recollir/tgik-playlist

Episode 016-020

---

episodes/021/README.md
episodes/022/README.md
episodes/023/README.md
episodes/024/README.md
episodes/025/README.md

Porting episode 021-025 from recollir/tgik-playlist

Episode 021-025

---

episodes/026/README.md
episodes/027/README.md
episodes/028/README.md
episodes/029/README.md
episodes/030/README.md

Porting episode 026-030 from recollir/tgik-playlist

Episode 026-030

---

episodes/031/README.md
episodes/032/README.md
episodes/033/README.md
episodes/034/README.md
episodes/035/README.md

Porting episode 031-035 from recollir/tgik-playlist.

Episode 031-035

---

episodes/039/yaml/05-dex/03-dex-configmap.yaml
episodes/039/yaml/05-dex/05-dex-deployment.yaml
episodes/039/yaml/06-gangway/02-config.yaml
episodes/039/yaml/06-gangway/03-gangway.yaml

Minor tweaks from live stream

---

episodes/038/README.md

Writing article on my blog about the success story of running KATA with nested virtualization enabled.
BTW, I am still waiting for the AWS support team to reply to my case "Enabling nested Virtualization with EC2"

feat: KATA Containers - Overcome the issue of nested virtualization using GCP

---

episodes/038/README.md

Add link to gVisor versus Katacontainers StackOverflow discussion
referenced in chat for this episode.

038 - Add link to gVisor versus Kata SO discussion

---

episodes/episode_template.md

Add a notes template for each episode

---

episodes/040/README.md

This adds YouTube timestamp shortcuts to the index. 

Add timestamps to the notes

---

episodes/041/README.md

Signed-off-by: Thorsten Schifferdecker <ts@systs.org>

Add link for the stateful_app for e041

---

playlist.md

Signed-off-by: Kris Nova <knova@heptio.com>

adds episodes 42 and 43 to the playlist

---

playlist.md

Thanks to @jpmondet for first opening https://github.com/heptio/tgik/pull/86 for this.
Signed-off-by: Carlisia <carlisia@grokkingtech.io>

Add 44 and 45

---

episodes/046/README.md
playlist.md

Signed-off-by: Carlisia <carlisia@grokkingtech.io>

Add episode 46

---

episodes/046/README.md
obs-config/youtube.css

Also tweaked the css for chat a bit.
I'm going to self merge this but /cc @carlisia @kris-nova @castrojo

Add notes for 046

---

episodes/048/README.md
playlist.md

Signed-off-by: Carlisia <carlisia@grokkingtech.io>

Add 048: Harbor

---

episodes/050/README.md
episodes/050/kubicorn/amazon_k8s_ubuntu_16.04_master.sh
episodes/050/kubicorn/tgik-weave-cluster/cluster.yaml

Signed-off-by: Kris Nova <kris@nivenly.com>

Adding weave kube install

---

episodes/049/README.md
playlist.md

Signed-off-by: David Coronel <davecoronel@gmail.com>

Updated Table of Contents for episode 049

---

episodes/051/README.md
episodes/episode_template.md
playlist.md

Add episode 51, update template and playlist

---

episodes/future-01/README.md
playlist.md

Postpone Contour episode

---

episodes/052/README.md

Prep for 52

---

episodes/027/README.md

that link is for the Helm episode

fix episode 27 youtube link

---

episodes/056/README.md

Update #56 based on hackmd

---

episodes/052/README.md
episodes/053/README.md
episodes/054/README.md

Some of the notes were still in the live documents and not committed to github.

Rebase the live notes and actual notes together

---

episodes/058/README.md

Prep for episode 58.

---

episodes/kubecon-seattle-2018/kind/kind_test.go
episodes/kubecon-seattle-2018/main.go

Adding kind source code

---

episodes/055/README.md

Copying over hackmd https://hackmd.io/ty7e6WPVRduEcTp0NkT2dg?edit

HackMD 055 Notes 

---

episodes/064/README.md
episodes/064/gke-hello-world/.gitignore
episodes/064/gke-hello-world/Pulumi.dev.yaml
episodes/064/gke-hello-world/Pulumi.yaml
episodes/064/gke-hello-world/config.ts
episodes/064/gke-hello-world/index.ts
episodes/064/gke-hello-world/kubeconfig
episodes/064/gke-hello-world/package-lock.json
episodes/064/gke-hello-world/package.json
episodes/064/gke-hello-world/tsconfig.json
playlist.md

Episode 064 readme and such

---

episodes/065/README.md
episodes/065/checklist.md

Signed-off-by: Duffie Cooley <dcooley@heptio.com>

065 initial

---

playlist.md

Signed-off-by: Duffie Cooley <dcooley@heptio.com>

updated playlist.md with ep 065

---

documentation/README.md

Swap out Jonas for Marissa

---

episodes/070/README.md

Add skeleton for Episode 70

---

episodes/070/README.md
episodes/070/agent.json
episodes/070/ca.json
episodes/070/sample-config
episodes/070/server.json

Add details from 070

---

episodes/071/README.md
playlist.md

Prep for episode 71

---

episodes/072/contour-kustomize/01-common.yaml
episodes/072/contour-kustomize/02-contour.yaml
episodes/072/contour-kustomize/02-rbac.yaml
episodes/072/contour-kustomize/02-service.yaml
episodes/072/contour-kustomize/kustomization.yaml
episodes/072/kuard-kustomize/deployment.yaml
episodes/072/kuard-kustomize/ingress.yaml
episodes/072/kuard-kustomize/kuard.config
episodes/072/kuard-kustomize/kustomization.yaml
episodes/072/kuard-kustomize/service.yaml
episodes/072/kuard-kustomize/static-cm.yaml
playlist.md

Files and notes for 072

---

episodes/073/README.md
playlist.md

Prep for episode 73

---

episodes/073/README.md
episodes/074/README.md
playlist.md

Prepping for 74

---

episodes/072/README.md

Forgot to check in readme for 072!

---

episodes/080/README.md
playlist.md

Add episode 80

---

episodes/082/README.md
playlist.md

Notes for 082

---

episodes/083/README.md
playlist.md

Add notes for 083

---

mc.yaml

Add the yaml file I started with

---

episodes/083/README.md

Pointer to code repo

---

README.md

Update link to playlist and update some branding

---

README.md

Updating the YouTube link to the new VMware Cloud Native Apps channel. Keep up the great work! :)
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Fix YouTube Link

---

episodes/094/README.md
episodes/095/README.md
episodes/095/kind/canal.yaml
episodes/095/kind/config
episodes/095/kind/fix_sysctls.sh
episodes/095/manifests/dind/deploy-dind-no-privs.yaml
episodes/095/manifests/dind/dind-no-privs.yaml
episodes/095/manifests/dind/dind-privs.yaml
episodes/095/manifests/k8s_root/r00t.yaml
playlist.md

added episode 94 and 95

---

episodes/096/README.md
episodes/096/kind/canal.yaml
episodes/096/kind/config
episodes/096/kind/fix_sysctls.sh
episodes/096/my-scheduler/config
episodes/096/my-scheduler/my-scheduler.yaml
episodes/096/my-scheduler/pod-my-scheduler.yaml
playlist.md

adding 096

---

episodes/078/README.md

added manifest link for 078

---

documentation/README.md

Per [internal] convo with Jorge.

todo: boschem -> ajgrey

---

episodes/100/README.md

episode 100

---

episodes/098/README.md

Noticed that the notes are missing, so got them from https://hackmd.io/qOYUjrmoSvyNnoT2eiJgIA?view and pushed them here.

Add episode 098

---

episodes/104/README.md
playlist.md

added episode 104

---

episodes/105/README.md
episodes/105/redis.yaml
playlist.md

Add episode 105

---

episodes/107/README.md
episodes/107/kind/fluent-bit/Chart.yaml
episodes/107/kind/fluent-bit/OWNERS
episodes/107/kind/fluent-bit/README.md
episodes/107/kind/fluent-bit/manifest.yaml
episodes/107/kind/fluent-bit/templates/NOTES.txt
episodes/107/kind/fluent-bit/templates/_helpers.tpl
episodes/107/kind/fluent-bit/templates/cluster-role.yaml
episodes/107/kind/fluent-bit/templates/cluster-rolebinding.yaml
episodes/107/kind/fluent-bit/templates/config.yaml
episodes/107/kind/fluent-bit/templates/daemonset.yaml
episodes/107/kind/fluent-bit/templates/psp.yaml
episodes/107/kind/fluent-bit/templates/secret.yaml
episodes/107/kind/fluent-bit/templates/service.yaml
episodes/107/kind/fluent-bit/templates/serviceaccount.yaml
episodes/107/kind/fluent-bit/templates/servicemonitor.yaml
episodes/107/kind/fluent-bit/templates/tests/test-configmap.yaml
episodes/107/kind/fluent-bit/templates/tests/test.yaml
episodes/107/kind/fluent-bit/values.yaml
episodes/107/kind/fluentd-elasticsearch/es-service.yaml
episodes/107/kind/fluentd-elasticsearch/es-statefulset.yaml
episodes/107/kind/fluentd-elasticsearch/images
episodes/107/kind/fluentd-elasticsearch/kibana-deployment.yaml
episodes/107/kind/fluentd-elasticsearch/kibana-service.yaml
episodes/107/kind/kind/adv-audit.yaml
episodes/107/kind/kind/config
episodes/107/kind/notes
playlist.md

added episode 107

---

episodes/110/README.md
episodes/110/capd-v3/.envrc
episodes/110/capd-v3/LICENSE
episodes/110/capd-v3/Makefile
episodes/110/capd-v3/README.md
episodes/110/capd-v3/clusterctl.yaml
episodes/110/capd-v3/clusters/base/cluster.yaml
episodes/110/capd-v3/clusters/base/cp0.yaml
episodes/110/capd-v3/clusters/base/cp1.yaml
episodes/110/capd-v3/clusters/base/cp2.yaml
episodes/110/capd-v3/clusters/base/kustomization.yaml
episodes/110/capd-v3/clusters/base/nodes.yaml
episodes/110/capd-v3/clusters/c1/kustomization.yaml
episodes/110/capd-v3/clusters/c2/kustomization.yaml
episodes/110/capd-v3/clusters/c3/kustomization.yaml
episodes/110/capd-v3/infrastructure-docker/v0.3.2/cluster-template.yaml
episodes/110/capd-v3/infrastructure-docker/v0.3.2/infrastructure-components.yaml
episodes/110/capd-v3/infrastructure-docker/v0.3.2/metadata.yaml
episodes/110/capd-v3/resources/images.list
episodes/110/capd-v3/resources/kind.yaml
episodes/110/capd-v3/resources/kpath

resources for episode 110

---

episodes/120/README.md
playlist.md

adding ep 120

---

episodes/121/README.md
episodes/122/README.md
playlist.md

adding 121 and 122

---

episodes/119/manifests/user.yaml

@joshrosso this is what was missing to check for a key existence.

Fix rego policy to check for securityContext existence

---

episodes/124/README.md
playlist.md

Notes for 124

---

episodes/076/README.md

Hackmd link: https://hackmd.io/BGeIboF-SYGI-5zKUeqkrg?both

Add the forgotten tgik note, episode 076

---

episodes/128/README.md
episodes/129/README.md
episodes/130/README.md
playlist.md

Signed-off-by: Paul Balogh <javaducky@gmail.com>

Adding notes from episodes 128, 129, and 130

---

episodes/131/README.md
playlist.md

Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

add episode 131

---

documentation/README.md

Adding more detail on pre-show prep.

Add more assistant steps

---

episodes/138/README.md
episodes/138/install-scripts/harbor/README.md
episodes/138/install-scripts/harbor/values-harbor.yaml
episodes/138/install-scripts/infra/cluster-issuer.yaml
episodes/138/install-scripts/infra/external-dns.yaml
episodes/138/install-scripts/infra/install.sh

Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

tgik episode 138

---

playlist.md

Signed-off-by: Paul Czarkowski <username.taken@gmail.com>

update playlist for ep 138

---

episodes/140/README.md

Episode 140 boilerplate

---

episodes/143/README.md
playlist.md

This PR adds episode 143 from 1/22/21.

Add episode 143

---

episodes/145/README.md
playlist.md

Ref https://github.com/vmware-tanzu/tgik/issues/355

Show Notes for #145, Duck Typing in Kubernetes

---

episodes/147/README.md
playlist.md

Resolves #58
Signed-off-by: Luke Short <ekultails@gmail.com>

Add episode 147 CoreDNS notes

---

obs-config/scenes/tgik-windows-evana.json

In case it's useful to someone else.

Add Windows OBS config from evana

---

episodes/151/README.md
episodes/151/sleep.yaml

episode 151: KPNG and Kube Proxy

---

episodes/162/README.md

Signed-off-by: jay vyas <jvyas@vmware.com>

Episode 162: CNI code surf

---

episodes/162/README.md

Signed-off-by: jay vyas <jvyas@vmware.com>

Add co hosts

---

episodes/164/README.md

Signed-off-by: Ricardo Katz <rkatz@vmware.com>
Adding episode 164

Add episode 164

---

episodes/153/README.md

Signed-off-by: Yogendra Rampuria (Yogi) <yogendrarampuria@gmail.com>

Adding 153 notes

---

CODE-OF-CONDUCT.md
playlist.md

Removed "Heptio" from the title and added missing episodes to the playlist. Some episodes lack folders.

Update CODE-OF-CONDUCT.md and playlist

---

documentation/README.md

clarify a couple of things i got confused about

streaming: Couple of quick notes for stuff i got confused with 

---

episodes/158/README.md

Episode 158 - Cluster API Tinkerbell

---

README.md

The Nov 26, 2021 episode will be hosted in the APAC friendly time - 9AM GMT / 2:30PM IST / 8PM AEDT

Add the time for Nov 26 episode
